### ISSUE TITLE
Highscore human readable

### ISSUE THREAD

**Issue by Sogolumbo** [bydariogamer/beatgame#16]
Why do you want to make the highscore file non-human-readable?

We will not be able to make it impossible to temper with the highscore (even if we encrypt the file), because the program is open source.

**Comment by bydariogamer** [comment]
But it is more difficult. Don't you lock you house? Someone could break into however, but at least it is more difficult... Maybe this is not the best approach, but we need some kind of obfuscation so a person who knows no programming (and even if you know programming, it is not that easy to break the code however) can't cheat.
Now we have to decide what to do:
1. We keep it like this, so the data can't be actually used but when the level is loaded, because we need to know the hash to get the score.
2. We make a system like the one from your PR and we add at the end of each line a hash with some check, like the hash of an iterator containing both the song and the score. If we want to make it even more hard to break all the hash could be in an only line at the end of the file. That would include a 'parsing' step to match the level with it's last hash but seems not that difficult.
I think option 2 is better, and maybe the first option is enough.

**Comment by Sogolumbo** [comment]
I really don't like security by obscurity (It doesn't work if the secrets are public). 
Also you still didn't name a reason why we should 'protect' the highscore. It's not published online or anything. I really don't care if anybody tampers with their highscore to impress their friends.
I think it would be nice if the score would be human readable. Adding a confirmation hash at the end seems like a better solution to me.

**Comment by Sogolumbo** [comment]
I gues most people would share their highscores with a screenshot. So editing the screenshot will always be a workaround. Our only goal would be making it harder to change the file than to change the screenshot. Anything beyond that is kind of a waste of time.

**Comment by bydariogamer** [comment]
I can make the file human-readable but have some kind of check. But I guess you are right.
Also, yea, I think security by obscurity is not the best approach...

**Comment by bydariogamer** [comment]
I really like the method u used to store high-scores (at least is working an not buggy... we can't say the same about mine).

**Comment by bydariogamer** [comment]
I think we are done with your method by now... I have an idea on how to use it, I will push to dev branch
